### PR TITLE
Homepage template

### LINKED ISSUE #115: Templatise “homepage”
It might be useful to templatise homepage so users can set their own content there (also for us to build SRE Challenges as extensions)

### PR DESCRIPTION
**Pull request by rin-st**
To test: 
Default page:
```
yarn cli
```

Challenge 0 homepage:

```
yarn cli challenge-0-homepage -e scaffold-eth/create-eth-extensions:sre-challenge-0
```

extension (only main page for now): https://github.com/scaffold-eth/create-eth-extensions/tree/sre-challenge-0

Fixes #115

### CODE REVIEW

**Review by technophile-04 — COMMENTED** [review]
Umm @rin-st what if take take the approach similar to Header instead of letting people to revamp whole thing? 

For example maybe we could have semantic naming similar to how we have have in `Header.args.mjs` eg: `menuImports`, `menuObjects`? 

In this case probably we could allow people editing : 

Screenshot 2024-09-13 at 8 18 36 PM


some thinking out loud varibale names: 

 `greetingsText`, `description`, `cardIconsImports`, `cardObject`? 
 
 We might need to update base SE-2 with making those stuff a bit dynamic for eg: `cardsObject` etc
 
 I think this will limit people doing from crazy stuff on home page itself, they always have option to do crazy stuff on their `/extension-page`. 
 
 what do you think? Also cc @carletex

**Comment by carletex** [comment]
Thanks for this @rin-st !!

> For example maybe we could have semantic naming similar to how we have have in Header.args.mjs eg: menuImports, menuObjects?

Yes, allowing people to just rewrite the whole page might be too much. I think finding a balance somewhere in the middle could be nice. 

An initial idea:

- Let's leave Welcome to SE-2 hardcoded
- Would it be possible to render the extension name dynamically? like
```
     Welcome to 
   Scaffold-ETH 2
(erc-721 extension)
```
- Allow people to rewrite the description completely (no append, just substitute)
image

Cards are a bit more noisy (with the icon import, link etc), so I left it out for intentionally for the first iteration.

@rin-st could you create a separate PR with this? So we can test both scenarios... and tinker in the new PR too.

**Comment by rin-st** [comment]
I agree, it could be too much to allow full page rewrite. I changed it fully just because I wanted challenge page to be the same as in original se-2-challenges.

> An initial idea:
> Let's leave Welcome to SE-2 hardcoded
> Would it be possible to render the extension name dynamically? like
> Allow people to rewrite the description completely (no append, just substitute)

So for example SRE-Challenges extensions will look something like this?
image

Or Home page (SE-2 Welcome page), main challenge page, ...all other challenge pages, debug?

image

**Comment by carletex** [comment]
I think what's shown in the image is great!! Yes, might be a bit verbose with the "Welcome" stuff, but it's not too crazy and I kind of link the SE-2 reference.

Thanks Rinat!

**Comment by rin-st** [comment]
v2: https://github.com/scaffold-eth/create-eth/pull/121

**Comment by technophile-04** [comment]
Closing this in favour of #121

**Pull request closed without merging**
