### PR TITLE
Template for externalContracts.ts

### PR DESCRIPTION
**Pull request by moltam89**
Hey guys,

I'm working on a Uniswap V2 swap [extension](https://github.com/moltam89/uniswap-v2-swap/blob/da864ac3347cad4181dd594e9a8686338a66fffb/extension/packages/nextjs/contracts/externalContracts.ts.args.mjs#L2103), where I'd need to list several contracts in the **externalContracts** file, so I created a template for it.

I can see that there are ongoing conversations about templating, let me know if this is the right direction and I'll add the changeset file and  update the [TEMPLATE-FILES.md ](https://github.com/scaffold-eth/create-eth/blob/main/contributors/TEMPLATE-FILES.md) description.

Cheers,
Tamas

### CODE REVIEW

**Review by technophile-04 — APPROVED** [review]
Thanks @moltam89! We have been planning to do this and the changes looks good. 

Let's see what others have to say regarding this : 

1. Security : 

There might a case where a fraud could trick users in installing their extension and interacting with some unkown contract.  

^ lol a very rare case and I might be thinking too much. 


2. Should we allow people to make just pass an part object like a  chain object? (thinking of future with multiple extension) 

I mean passing whole object makes and a way to go until we support multiple extension. 

--- 

Also @moltam89 could you add the changeset? make sure you choose `patch` instead of major or minor, lol last time at #129 you added it as `minor` version.

**Comment by moltam89** [comment]
Thanks @technophile-04 !

I've added the changeset with patch.

**Comment by rin-st** [comment]
> There might a case where a fraud could trick users in installing their extension and interacting with some unkown contract.

That's why we're telling `You are using a third-party extension. Make sure you trust the source ... ` when installing external extension 🙂 

> Should we allow people to make just pass an part object like a chain object? (thinking of future with multiple extension)

Let's add these changes when needed

Lgtm! Thanks!

**Review by rin-st — APPROVED** [review]

**Comment by technophile-04** [comment]
Thanks all!!

**Comment by carletex** [comment]
Much needed template, thanks!!

**Pull request merged**
