### PR TITLE
backmerge 16/12/24

### PR DESCRIPTION
**Pull request by technophile-04**
- Follow root level naming convention (https://github.com/scaffold-eth/scaffold-eth-2/pull/1006)
- Fix useScaffoldEventHistory duplicated events (https://github.com/scaffold-eth/scaffold-eth-2/pull/1014)
- feat: disable vercel telemetry (https://github.com/scaffold-eth/scaffold-eth-2/pull/1012)
- Optional chainId config in Scaffold hooks (https://github.com/scaffold-eth/scaffold-eth-2/pull/931)
- Foundry improvements (https://github.com/scaffold-eth/scaffold-eth-2/pull/1011)
- make `useScaffoldWriteContract` & `useDeployedContractInfo` backward compatible (https://github.com/scaffold-eth/scaffold-eth-2/pull/1015)
- fix: move warnings to useEffect (https://github.com/scaffold-eth/scaffold-eth-2/pull/1016)

### To test: 

1. Clone `create-eth` repo
2. Switch to this branch: 
```
git pull && git switch backmerge-16-12-24
```
3. Start the dev server: 
```
yarn dev
```
4. Test instance: 

```
yarn cli
```

### CODE REVIEW

**Review by rin-st — APPROVED** [review]
Works great to me!

**Review by Pabl0cks — APPROVED** [review]
Looks great to me! GJ guys 🙌

**Comment by Pabl0cks** [comment]
This one looks good to me too 🙏: 
> make useScaffoldWriteContract & useDeployedContractInfo backward compatible (https://github.com/scaffold-eth/scaffold-eth-2/pull/1015)

**Review by rin-st — APPROVED** [review]

**Comment by technophile-04** [comment]
Merging this thanks all!

**Pull request merged**
