### PR TITLE
don't prompt for install + remove prettier plugins

### PR DESCRIPTION
**Pull request by technophile-04**
### Description: 

- Removed prompt for installing dependencies
   - `--skip-install` is an escape hatch (not completely sure if we should remove or keep it but sometimes its pretty handy)
- Removed prettiers plugins which were installed due to #55 + moved prettier to devDependency

### CODE REVIEW

**Comment by technophile-04** [comment]
Ohh strange, I just tried it with same options chosen / dir name and it seems to work for me : 

<details>

<summary>
My ClI Log : 
</summary>

```
yarn cli

 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 | Create Scaffold-ETH 2 app |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+

? Your project name: ffd
? What solidity framework do you want to use? hardhat


✔ 📁 Create project directory /Users/shivbhonde/Desktop/Github/create-eth/ffd
✔ 🚀 Creating a new Scaffold-ETH 2 app in ffd
✔ 📦 Installing dependencies with yarn, this could take a while
✔ 🪄 Formatting files
✔ 📡 Initializing Git repository



  Congratulations! Your project has been scaffolded! 🎉

  Next steps:

  cd ffd

        Start the local development node
        yarn chain

        In a new terminal window, deploy your contracts
        yarn deploy

        In a new terminal window, start the frontend
        yarn start

  Thanks for using Scaffold-ETH 2 🙏, Happy Building!


```


</details>

**Review by rin-st — APPROVED** [review]
My bad, I had test data from previous pr's 🤦 

Good job, works well!

**Comment by carletex** [comment]
Works great  @technophile-04 

Good stuff!!

**Comment by carletex** [comment]
BTW, should have we added a changeset here?

**Comment by technophile-04** [comment]
> BTW, should have we added a changeset here?

Ohh yess! forgot about it :(, also btw could configure https://github.com/apps/changeset-bot in this repo which reminds to add changeset if necessary

**Comment by carletex** [comment]
That bot is nice too.

In any case, we need some kind of tweak in our workflow (release branches or auto-tag commits with versions or force changeset on PRs...) because if not it's hard to lose track code and the published npm version.

**Pull request merged**
