### PR TITLE
allow any case extension name in dev mode

### LINKED ISSUE #100: Unable to run `cli -e {extension} --dev` with extensions with CAPS
[On line 77 in `src/utils/parse-arguments-into-options.ts`](https://github.com/scaffold-eth/create-eth/blob/main/src/utils/parse-arguments-into-options.ts#L77) we parse all the arguments to lower case. This results in the users not being able to run extensions in dev-mode which has capital letters in their name.

```
$ yarn cli -e ALL_OR_some_CAPS --dev

 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 | Create Scaffold-ETH 2 app |
 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+

Extension not found in "externalExtensions/all_or_some_caps"
$ ls externalExtensions/
ALL_OR_some_CAPS
```

I don't know the side-effects of removing the line entirely. I could make a PR where I do it for all other options but `-e`. LMK  what you think.

### PR DESCRIPTION
**Pull request by technophile-04**
### Description 

Fixes #100

### CODE REVIEW

**Review by rin-st — APPROVED** [review]
lgtm!

**Comment by rin-st** [comment]
some nit questions:
Why only dev mode? If user wants to uppercase some characters of his folder, I think it's high chance that he will uppercase also repo name/branch name

**Comment by technophile-04** [comment]
>  If user wants to uppercase some characters of his folder, I think it's high chance that he will uppercase also repo name/branch name

Yeah actually I thought about it in beginning but didn't do it since githubuserName and repoName are normalized internally in github I think and not case sensitive because github won't let you create two repos with same name eg: "my-test-repo" & "My-test-Repo" they both are same. 

But yeah just noticed that branch names are case-sensitive you could have two different branches as "main" & "Main", so updated it and now it always uses original extension name passed at https://github.com/scaffold-eth/create-eth/pull/101/commits/c04c1d98d0650bdb78bcdbbb618293dd0754b82f but also handled a small case where if people want to use curated extension we lowercase extensionName before looking up for its value in `CURATED_EXTENSIONS` dictionary

**Review by rin-st — APPROVED** [review]
Lgtm!

**Pull request merged**
