### PR TITLE
Forking url for foundry

### PR DESCRIPTION
**Pull request by moltam89**
Hey guys,

Currently foundry uses the public mainnet RPC for forking, which can be problematic, see https://github.com/scaffold-eth/scaffold-eth-2/pull/955#discussion_r1794469370.

Hardhat already uses the FORKING_URL environment variable.

**Note:**
I might have had to send this PR to https://github.com/scaffold-eth/scaffold-eth-2/tree/foundry, but this branch seems to be older than this repo (still uses alchemy API key).

Cheers,
Tamas

### CODE REVIEW

**Comment by technophile-04** [comment]
> I might have had to send this PR to https://github.com/scaffold-eth/scaffold-eth-2/tree/foundry, but this branch seems to be older than this repo (still uses alchemy API key).

Ohh yeah, @moltam89 do you want to update that branch with alchemy key changes and also add this changes to that PR? Ideally we are trying to keep that branch and this sync for now 🙌

**Comment by moltam89** [comment]
Yeah, I'll look into this (probably next week) and try to apply the changes from here to the scaffold-eth-2/foundry branch.

**Comment by technophile-04** [comment]
Thanks Tam! I just updated the SE-2 foundry branch with (alchemy stuff) but can make this PR changes to SE-2 foundry

**Comment by moltam89** [comment]
Thanks @technophile-04 !

Here is the SE2 version of this:https://github.com/scaffold-eth/scaffold-eth-2/pull/974

**Comment by technophile-04** [comment]
Closing this, ref https://github.com/scaffold-eth/scaffold-eth-2/pull/974#issuecomment-2490826429

**Pull request closed without merging**
