### PR TITLE
Weekly cli backmerge

### PR DESCRIPTION
**Pull request by technophile-04**
### Description : 

- Bump wagmi, viem and rainbowkit versions (scaffold-eth#849)
- Add default favicon (scaffold-eth#851)

NOTE: We shouldn't squash and merge this, instead do a normal merge

### CODE REVIEW

**Comment by technophile-04** [comment]
Tested it nicely, also subgraph + foundry :) 

repo link : https://github.com/technophile-04/subgraph-foundry

live app : https://subgraph-foundry-sepolia.vercel.app/

**Review by rin-st — APPROVED** [review]
Working great, thanks!

**Review by Pabl0cks — APPROVED** [review]
Tested it nicely and it's looking great to me 🙌 

Tried regular hardhat, hardhat + external extension, foundry + subgraph curated extension.

**Comment by technophile-04** [comment]
Tysm all merging this 🙌

**Pull request merged**
