### PR TITLE
Update extensions styles

### PR DESCRIPTION
**Pull request by rin-st**
Origin https://github.com/scaffold-eth/create-eth-extensions/pull/29#issuecomment-2462205191

Adds possibility
- to import to global css
- to set global classnames, for example in case of challenge 0 extension it is `font-space-grotesk`
- to change thumbnail
- to change metadata titleTemplate

+ updated tailwind config template to work with objects instead of strings

to test run from this branch
```
yarn dev
```
and then

```
yarn cli -e scaffold-eth/create-eth-extensions:update-ch0-styles
```

PR for challenge-0 extension changes https://github.com/scaffold-eth/create-eth-extensions/pull/36

### CODE REVIEW

**Review by Pabl0cks — COMMENTED** [review]
Thanks for tackling this @rin-st !!

It worked great with `update-ch0-styles` branch, but just tried it with the old ch0 branch, using `yarn cli -e scaffold-eth/create-eth-extensions:challenge-0-v2` , and it doesn't create my tailwind file correctly, ending in a page without styles:

image

Update:
- Tried with a different extension (curated erc-20) and it worked fine.
- With `challenge-0-v2` extension, my generated tailwind file has some single quotes `'` and escaped newlines `\n`, if I delete them the website looks fine:

image

**Comment by rin-st** [comment]
> Thanks for tackling this @rin-st !!
> 
> It worked great with `update-ch0-styles` branch, but just tried it with the old ch0 branch, using `yarn cli -e scaffold-eth/create-eth-extensions:challenge-0-v2` , and it doesn't create my tailwind file correctly, ending in a page without styles:


It shouldn't work with old branch since I changed tailwind config generating. In new branches it uses object instead of old stringifyed version, so that's why these branches are incompatible. The thing we should check is that new branches works fine together, and also works with other extensions. As I understand the only things that could break are third-party extensions which use tailwind config. But we can let them now in the extensions chat after we merge this

> 
> Update:
> 
> * Tried with a different extension (curated erc-20) and it worked fine.
> * With `challenge-0-v2` extension, my generated tailwind file has some single quotes `'` and escaped newlines `\n`, if I delete them the website looks fine:
>

**Comment by rin-st** [comment]
Update: I merged https://github.com/scaffold-eth/create-eth-extensions/pull/36 so now use `challenge-0-v2` extension branch instead of `update-ch0-styles`

**Review by Pabl0cks — APPROVED** [review]
> Update: I merged https://github.com/scaffold-eth/create-eth-extensions/pull/36 so now use challenge-0-v2 extension branch instead of update-ch0-styles

Looks good to me!! 

Don't think many of the current extensions have custom tailwind file, and probably the dev using those extension will figure out fast how to fix the generated tailwind file.

**Review by carletex — APPROVED** [review]

**Pull request merged**
