### PR TITLE
weekly cli backmerge

### PR DESCRIPTION
**Pull request by technophile-04**
### Description: 

- revert scaffold-eth#875 ([scaffold-eth#905](https://github.com/scaffold-eth/scaffold-eth-2/pull/905))

@rin-st could you please try the linting in vscode? : 

1. Start the CLI dev server
```
yarn dev
```

2. Create an instance: 

```
yarn cli -s hardhat
```

3. In the instance created, try out if lint is working or not in vscode. Test snippet: 

```ts
  const [count, setCount] = useState(0);
  const [name, setName] = useState("shiv");
  // should get an eslint error
  const x = "shiv";

  useEffect(() => {
    setCount(count + 1);
    console.log(count);
    setName("shiv");
    console.log(name);
    // should get an eslint warning 
  }, [count]);

```

### CODE REVIEW

**Comment by carletex** [comment]
Thank you @technophile-04 !!

Let's publish a new create-eth version when this is merged

**Comment by rin-st** [comment]
It works!
image

Notes:
1. for some reason it asked to install yarn 3.5.0
Screenshot 2024-08-12 at 12 26 58

2. When running yarn next:lint it shows warning regarding ts version
```
yarn next:lint
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0

YOUR TYPESCRIPT VERSION: 5.5.3

Please only submit bug reports when using the officially supported version.

=============

./app/page.tsx
15:9  Error: 'x' is assigned a value but never used.  @typescript-eslint/no-unused-vars
23:6  Warning: React Hook useEffect has a missing dependency: 'name'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
```

**Review by rin-st — APPROVED** [review]

**Comment by technophile-04** [comment]
Thanks Rinat!! 

Actually regarding the warning of ts version is present on git clone se-2 version as well. If you first time clone the repo, yarn install and run `yarn next:lint` you should get it. It was introduced in https://github.com/scaffold-eth/scaffold-eth-2/pull/885. We could maybe lower the TS version b/w that range in future PR? 

But yeah merging this for now since everything seem to work 🙌

**Comment by rin-st** [comment]
> We could maybe lower the TS version b/w that range in future PR?

I think it's not critical at all, we can live with it for some time :)

**Pull request merged**
